# Generated by Django 5.1.2 on 2026-10-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenciaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('medio', models.CharField(choices=[('QR', 'QR'), ('MANUAL', 'Búsqueda Manual')], default='QR', max_length=10)),
            ],
        ),
    ]
