# Generated by Django 5.1.2 on 2026-10-09 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitados', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitado',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
