# Generated by Django 5.1.2 on 2026-10-02 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instructores', '0001_initial'),
        ('personas', '0001_initial'),
        ('programas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_instructor', to='personas.persona'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='programas',
            field=models.ManyToManyField(blank=True, related_name='instructores', to='programas.programatecnico'),
        ),
    ]
