# Generated by Django 5.1.2 on 2026-10-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructores', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='cargo',
            field=models.CharField(blank=True, default='Instructor', max_length=150, null=True, verbose_name='Cargo / Perfil'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='entidad',
            field=models.CharField(blank=True, default='SENA', max_length=200, null=True, verbose_name='Entidad / Centro SENA'),
        ),
    ]
