# Generated by Django 5.1.2 on 2026-10-09 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0006_alter_persona_tipo_persona'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.CharField(blank=True, default='', max_length=200)),
                ('cargo', models.CharField(blank=True, default='', max_length=150)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_visitante', to='personas.persona')),
            ],
        ),
    ]
