# Generated by Django 5.1.2 on 2026-10-08 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0003_persona_correo_personal_persona_correo_sena_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(blank=True, max_length=150, null=True, verbose_name='Cargo / Función')),
                ('area_responsabilidad', models.CharField(blank=True, max_length=200, null=True, verbose_name='Área / Punto de atención')),
                ('activo', models.BooleanField(default=True)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_organizador', to='personas.persona')),
            ],
            options={
                'verbose_name': 'Organizador',
                'verbose_name_plural': 'Organizadores',
            },
        ),
    ]
