# Generated by Django 5.1.2 on 2026-10-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizador',
            name='entidad',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Entidad / Empresa / Comité organizador'),
        ),
    ]
