# Generated by Django 5.1.2 on 2026-10-08 14:58

import apps.programas.models
from django.db import migrations, models


def _populate_codigos_programas(apps, schema_editor):
    ProgramaTecnico = apps.get_model('programas', 'ProgramaTecnico')
    for p in ProgramaTecnico.objects.all().order_by('id'):
        p.codigo = f'PR-{p.id:04d}'
        p.save(update_fields=['codigo'])


def _reverse_populate_programas(apps, schema_editor):
    ProgramaTecnico = apps.get_model('programas', 'ProgramaTecnico')
    ProgramaTecnico.objects.all().update(codigo='')


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programatecnico',
            name='codigo',
            field=models.CharField(max_length=30, verbose_name='Código Programa'),
        ),
        migrations.RunPython(
            _populate_codigos_programas,
            _reverse_populate_programas,
        ),
        migrations.AlterField(
            model_name='programatecnico',
            name='codigo',
            field=models.CharField(default=apps.programas.models._generar_codigo_programa, max_length=30, unique=True, verbose_name='Código Programa'),
        ),
    ]
