# Generated by Django 5.1.2 on 2026-10-02 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0001_initial'),
        ('instituciones', '0001_initial'),
        ('instructores', '0001_initial'),
        ('personas', '0001_initial'),
        ('programas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=40)),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('INSCRITO', 'Inscrito'), ('APROBADO', 'Aprobado'), ('RETIRADO', 'Retirado')], default='INSCRITO', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='eventos.evento')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='instituciones.institucioneducativa')),
                ('instructor_responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_dirigidos', to='instructores.instructor')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='programas.programatecnico')),
            ],
        ),
        migrations.CreateModel(
            name='Aprendiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.CharField(default='11', max_length=10)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_aprendiz', to='personas.persona')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aprendices', to='proyectos.proyecto')),
            ],
            options={
                'ordering': ['persona__apellidos', 'persona__nombres'],
            },
        ),
        migrations.AddConstraint(
            model_name='proyecto',
            constraint=models.UniqueConstraint(fields=('evento', 'codigo'), name='uq_proyecto_evento_codigo'),
        ),
    ]
