# Generated by Django 5.1.2 on 2026-10-03 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituciones', '0002_alter_institucioneducativa_options_and_more'),
        ('instructores', '0002_initial'),
        ('programas', '0001_initial'),
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(db_index=True, max_length=7, unique=True)),
                ('grado', models.CharField(blank=True, default='11', max_length=10)),
                ('municipio', models.CharField(blank=True, max_length=100)),
                ('telefono_instructor', models.CharField(blank=True, max_length=30, null=True)),
                ('correo_instructor', models.EmailField(blank=True, max_length=180, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fichas', to='instituciones.institucioneducativa')),
                ('instructor_lider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_dirigidas', to='instructores.instructor')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fichas', to='programas.programatecnico')),
            ],
            options={
                'verbose_name': 'Ficha',
                'verbose_name_plural': 'Fichas',
                'ordering': ['numero'],
            },
        ),
        migrations.AddField(
            model_name='proyecto',
            name='ficha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos', to='proyectos.ficha'),
        ),
        migrations.AddConstraint(
            model_name='ficha',
            constraint=models.UniqueConstraint(fields=('numero',), name='uq_ficha_numero'),
        ),
    ]
