# Generated by Django 5.1.2 on 2026-10-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_ficha_proyecto_ficha_ficha_uq_ficha_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='aprendiz',
            name='cargo',
            field=models.CharField(blank=True, default='Aprendiz', max_length=150, null=True, verbose_name='Cargo / Rol'),
        ),
        migrations.AddField(
            model_name='aprendiz',
            name='entidad',
            field=models.CharField(blank=True, help_text='Normalmente la institución del Proyecto (se rellena automáticamente).', max_length=200, null=True, verbose_name='Entidad / I.E. / Colegio'),
        ),
    ]
