# Generated by Django 5.1.2 on 2026-10-02 19:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_unico', models.CharField(editable=False, max_length=40, unique=True)),
                ('token_verificacion', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('fecha_hora_entrega', models.DateTimeField(auto_now_add=True)),
                ('medio', models.CharField(choices=[('QR', 'QR'), ('MANUAL', 'Búsqueda Manual')], default='QR', max_length=10)),
            ],
        ),
    ]
