# Generated by Django 5.1.2 on 2026-10-02 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tiposervicio',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_servicio', to='eventos.evento'),
        ),
        migrations.AddConstraint(
            model_name='tiposervicio',
            constraint=models.UniqueConstraint(fields=('evento', 'nombre'), name='uq_tiposervicio_evento_nombre'),
        ),
    ]
