# Generated by Django 5.1.2 on 2026-10-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstitucionEducativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, unique=True)),
                ('municipio', models.CharField(max_length=100)),
                ('secretaria_educacion', models.CharField(blank=True, max_length=150)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Institución Educativa',
                'verbose_name_plural': 'Instituciones Educativas',
            },
        ),
    ]
