# Generated by Django 5.1.2 on 2026-10-03 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institucioneducativa',
            options={'ordering': ['nombre'], 'verbose_name': 'Institución Educativa', 'verbose_name_plural': 'Instituciones Educativas'},
        ),
        migrations.AddField(
            model_name='institucioneducativa',
            name='caracter',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Carácter'),
        ),
        migrations.AddField(
            model_name='institucioneducativa',
            name='celular_coordinador',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='institucioneducativa',
            name='correo_institucional',
            field=models.EmailField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='institucioneducativa',
            name='direccion',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='institucioneducativa',
            name='especialidad',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='institucioneducativa',
            name='nombre_coordinador',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='institucioneducativa',
            name='nombre_rector',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='institucioneducativa',
            name='sector',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='institucioneducativa',
            name='telefono_rector',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='institucioneducativa',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='institucioneducativa',
            name='zona',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
