# Generated by Django 5.1.2 on 2026-10-08 01:22

import apps.instituciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituciones', '0002_alter_institucioneducativa_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institucioneducativa',
            options={'ordering': ['municipio', 'nombre'], 'verbose_name': 'Institución Educativa', 'verbose_name_plural': 'Instituciones Educativas'},
        ),
        migrations.AddField(
            model_name='institucioneducativa',
            name='telefono',
            field=models.CharField(blank=True, help_text='Teléfono principal de la institución (opcional)', max_length=30, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='institucioneducativa',
            name='codigo',
            field=models.CharField(default=apps.instituciones.models._generar_codigo_ie, help_text='Identificador único automático (INS-XXXXXXX). Se genera al crear la institución.', max_length=30, unique=True, verbose_name='Código Único IE'),
        ),
        migrations.AlterField(
            model_name='institucioneducativa',
            name='secretaria_educacion',
            field=models.CharField(blank=True, max_length=150, verbose_name='Secretaría de Educación'),
        ),
    ]
