# Generated by Django 5.1.2 on 2026-10-08 14:58

import apps.instituciones.models
from django.db import migrations, models


def _populate_codigos_instituciones(apps, schema_editor):
    Municipio = apps.get_model('instituciones', 'Municipio')
    for m in Municipio.objects.all().order_by('id'):
        if not m.codigo or m.codigo.strip() == '':
            m.codigo = f'M-{m.id:04d}'
            m.save(update_fields=['codigo'])

    InstitucionEducativa = apps.get_model('instituciones', 'InstitucionEducativa')
    for ie in InstitucionEducativa.objects.all().order_by('id'):
        ie.codigo = f'IE-{ie.id:04d}'
        ie.save(update_fields=['codigo'])


def _reverse_populate_instituciones(apps, schema_editor):
    Municipio = apps.get_model('instituciones', 'Municipio')
    Municipio.objects.all().update(codigo=None)


class Migration(migrations.Migration):

    dependencies = [
        ('instituciones', '0004_municipio_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipio',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Municipio'),
        ),
        migrations.AlterField(
            model_name='institucioneducativa',
            name='codigo',
            field=models.CharField(help_text='Identificador único automático (IE-XXXX). Se genera al crear la institución.', max_length=30, verbose_name='Código Único IE'),
        ),
        migrations.RunPython(
            _populate_codigos_instituciones,
            _reverse_populate_instituciones,
        ),
        migrations.AlterField(
            model_name='municipio',
            name='codigo',
            field=models.CharField(blank=True, default=apps.instituciones.models._generar_codigo_municipio, max_length=10, null=True, unique=True, verbose_name='Código Municipio'),
        ),
        migrations.AlterField(
            model_name='institucioneducativa',
            name='codigo',
            field=models.CharField(default=apps.instituciones.models._generar_codigo_ie, help_text='Identificador único automático (IE-XXXX). Se genera al crear la institución.', max_length=30, unique=True, verbose_name='Código Único IE'),
        ),
    ]
