# Generated by Django 5.1.2 on 2026-10-03 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='correo_personal',
            field=models.EmailField(blank=True, max_length=180, null=True, verbose_name='Correo personal'),
        ),
        migrations.AddField(
            model_name='persona',
            name='correo_sena',
            field=models.EmailField(blank=True, max_length=180, null=True, verbose_name='Correo SENA'),
        ),
        migrations.AddField(
            model_name='persona',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
    ]
