# Generated by Django 5.1.2 on 2026-10-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_persona_correo_personal_persona_correo_sena_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='cargo',
            field=models.CharField(blank=True, help_text='Aprendiz · Instructor · Coordinador · Rector · Invitado especial · etc.', max_length=150, null=True, verbose_name='Cargo / Función / Rol en la Entidad'),
        ),
        migrations.AddField(
            model_name='persona',
            name='entidad',
            field=models.CharField(blank=True, help_text='SENA · I.E. · Colegio · Alcaldía · Empresa · etc.', max_length=200, null=True, verbose_name='Entidad / Institución / Empresa'),
        ),
    ]
