# Generated by Django 5.1.2 on 2026-10-09 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0005_persona_sincronizar_correo_visible_instructores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='tipo_persona',
            field=models.CharField(choices=[('APRENDIZ', 'Aprendiz'), ('INSTRUCTOR', 'Instructor'), ('INVITADO', 'Invitado'), ('ORGANIZADOR', 'Organizador'), ('VISITANTE', 'Visitante')], db_index=True, max_length=20),
        ),
    ]
