# Generated by Django 5.1.2 on 2026-10-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREATE', 'Crear'), ('UPDATE', 'Modificar'), ('DELETE', 'Eliminar'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('IMPORT', 'Importación'), ('ASISTENCIA', 'Asistencia'), ('REFRIGERIO', 'Refrigerio'), ('CERTIFICADO', 'Certificado')], db_index=True, max_length=20)),
                ('modulo', models.CharField(db_index=True, max_length=50)),
                ('entidad', models.CharField(max_length=100, null=True)),
                ('id_entidad', models.PositiveIntegerField(null=True)),
                ('datos', models.JSONField(null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
